divyamohan1993/divyamohan1993:

  #Learn about the distelli-manifest.yml at https://www.distelli.com/docs/reference/distelli-manifest
  PkgInclude:
    - '*'

  Build:
    - echo "Begin Build"

  PreInstall:
    - echo "Begin PreInstall"

  PostInstall:
    - echo "Begin PostInstall"

  Exec:
