name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Bugs, here and there... you know...! Thankyou for creating your first issue. Will be looked upon shortly."
        pr-message: "Thankyou for creating your pull request. We will look into it shortly."
